# Generated by Django 6.1 on 2026-09-17 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0009_sittingitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="sittingitem",
            name="grade_bands",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ComponentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("component_name", models.CharField(max_length=50)),
                ("component_position", models.PositiveSmallIntegerField()),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade_name", models.CharField(max_length=50)),
                (
                    "sitting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="exams.sitting",
                    ),
                ),
            ],
            options={
                "ordering": ["component_position", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sitting", "component_name"),
                        name="uq_one_result_per_component_per_sitting",
                    )
                ],
            },
        ),
    ]
