# Generated by Django 6.1 on 2026-09-25 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0010_sittingitem_grade_bands_componentresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("first_year", models.PositiveSmallIntegerField(unique=True)),
                ("last_year", models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                "ordering": ["first_year"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("first_year__lte", models.F("last_year"))),
                        name="ck_cycle_ends_after_it_starts",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CategoryRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.PositiveSmallIntegerField()),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("DIFFICULTY", "Difficulty"),
                            ("EXECUTION", "Execution"),
                            ("ARTISTRY", "Artistry"),
                        ],
                        max_length=10,
                    ),
                ),
                ("minimum_grade", models.CharField(max_length=50)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_requirements",
                        to="exams.cycle",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "dimension"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cycle", "category", "dimension"),
                        name="uq_one_minimum_per_category_dimension_per_cycle",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("category__gte", 1), ("category__lte", 4)),
                        name="ck_category_requirement_is_one_to_four",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("dimension__in", ["DIFFICULTY", "EXECUTION", "ARTISTRY"])
                        ),
                        name="ck_category_requirement_dimension_is_valid",
                    ),
                ],
            },
        ),
    ]
