# Generated by Django 6.1 on 2026-09-25 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0011_cycles_and_category_requirements"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsitting",
            name="candidate_number",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitting",
            name="override_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalsitting",
            name="override_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitting",
            name="candidate_number",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="sitting",
            name="override_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="overrides_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sitting",
            name="override_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddConstraint(
            model_name="sitting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("override_by__isnull", True), ("override_reason", "")),
                    models.Q(
                        ("override_by__isnull", False),
                        models.Q(("override_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="ck_sitting_override_has_official_and_reason",
            ),
        ),
    ]
