# Generated by Django 6.1 on 2026-09-25 15:17

from django.conf import settings
from django.db import migrations, models

import exams.models.sitting


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0013_fill_candidate_numbers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsitting",
            name="candidate_number",
            field=models.CharField(
                default=exams.models.sitting.new_candidate_number, max_length=8
            ),
        ),
        migrations.AlterField(
            model_name="sitting",
            name="candidate_number",
            field=models.CharField(
                default=exams.models.sitting.new_candidate_number, max_length=8
            ),
        ),
        migrations.AddConstraint(
            model_name="sitting",
            constraint=models.UniqueConstraint(
                fields=("exam", "candidate_number"),
                name="uq_one_candidate_number_per_exam",
            ),
        ),
    ]
