# Generated by Django 6.1 on 2026-09-25 15:34

from django.db import migrations, models

# The default "" is right for theory rows and WRONG for practical ones. No backfill:
# on 2026-09-25 no database held a sitting (dev had none, and nothing is deployed).
# A database that does must fill these from each sitting's exam components, by
# component_position, before certification reads them.


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0014_candidate_number_required_and_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentresult",
            name="aspect",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AddField(
            model_name="sittingitem",
            name="component_aspect",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
    ]
